version: '3.5'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./framework:/var/www/app
      - ./nginx-site.conf:/etc/nginx/conf.d/docker.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./framework:/var/www/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3386:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $_ENV['PASSWORD']
