version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/app
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - mysql
  php-fpm:
    image: php:8-fpm
    build:
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/app
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
