-- MySQL Script generated by MySQL Workbench
-- Mon Feb 21 20:22:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_home_lib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_home_lib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_home_lib` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `my_home_lib` ;

-- -----------------------------------------------------
-- Table `my_home_lib`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`author` (
  `author_id` INT(11) NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Автор',
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Автор книги';


-- -----------------------------------------------------
-- Table `my_home_lib`.`cover`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`cover` (
  `cover_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cover_name` VARCHAR(50) NOT NULL COMMENT 'Обложка, переплёт',
  PRIMARY KEY (`cover_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Обложка, переплёт';


-- -----------------------------------------------------
-- Table `my_home_lib`.`ISBN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`ISBN` (
  `isbn_id` INT(11) NOT NULL AUTO_INCREMENT,
  `isbn_number` INT(13) NOT NULL COMMENT 'Обложка, переплёт',
  PRIMARY KEY (`isbn_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Международный стандартный книжный номер';


-- -----------------------------------------------------
-- Table `my_home_lib`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`book` (
  `book_id` INT(11) NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(255) NOT NULL COMMENT 'Название книги',
  `publication_year` DATE NULL COMMENT 'Год выпуска',
  `book_case` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Полка, стеллаж',
  `numpage` INT(11) NULL DEFAULT NULL COMMENT 'Количествово страниц',
  `cover` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Обложка, переплёт',
  `ISBN` INT(13) NULL,
  PRIMARY KEY USING BTREE (`book_id`),
  CONSTRAINT `FK_cover`
    FOREIGN KEY (`book_id`)
    REFERENCES `my_home_lib`.`cover` (`cover_id`),
  CONSTRAINT `FK_ISBN`
    FOREIGN KEY (`book_id`)
    REFERENCES `my_home_lib`.`ISBN` (`isbn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Коллекция книг';


-- -----------------------------------------------------
-- Table `my_home_lib`.`author_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`author_data` (
  `author` INT(11) NOT NULL COMMENT 'Автор',
  `book` INT(11) NOT NULL COMMENT 'Название книги',
  INDEX `FK_author_idx` (`author` ASC) VISIBLE,
  INDEX `FK_book_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `FK_author`
    FOREIGN KEY (`author`)
    REFERENCES `my_home_lib`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_book`
    FOREIGN KEY (`book`)
    REFERENCES `my_home_lib`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_home_lib`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`collection` (
  `collection_id` INT(11) NOT NULL AUTO_INCREMENT,
  `collection_name` VARCHAR(255) NOT NULL COMMENT 'Сборник, коллекция',
  PRIMARY KEY (`collection_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Сборник, коллекция';


-- -----------------------------------------------------
-- Table `my_home_lib`.`collection_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`collection_data` (
  `collection` INT(11) NOT NULL DEFAULT '' COMMENT 'Сборник, коллекция',
  `book` INT(11) NOT NULL DEFAULT '' COMMENT 'Название книги',
  INDEX `FK_collection_idx` (`collection` ASC) VISIBLE,
  INDEX `FK_book_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `FK_collection`
    FOREIGN KEY (`collection`)
    REFERENCES `my_home_lib`.`collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_book`
    FOREIGN KEY (`book`)
    REFERENCES `my_home_lib`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Сборник, коллекция';


-- -----------------------------------------------------
-- Table `my_home_lib`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`genre` (
  `genre_id` INT(11) NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(50) NOT NULL COMMENT 'Жанр',
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Жанр книги';


-- -----------------------------------------------------
-- Table `my_home_lib`.`genre_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`genre_data` (
  `genre` INT(11) NOT NULL COMMENT 'Жанр',
  `book` INT(11) NOT NULL COMMENT 'Название книги',
  INDEX `FK_genre_idx` (`genre` ASC) VISIBLE,
  INDEX `FK_book_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `FK_genre`
    FOREIGN KEY (`genre`)
    REFERENCES `my_home_lib`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_book`
    FOREIGN KEY (`book`)
    REFERENCES `my_home_lib`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_home_lib`.`publishing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`publishing` (
  `publishing_id` INT(11) NOT NULL AUTO_INCREMENT,
  `publishing_name` VARCHAR(255) NOT NULL COMMENT 'Издательство',
  PRIMARY KEY (`publishing_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Издательство';


-- -----------------------------------------------------
-- Table `my_home_lib`.`publishing_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`publishing_data` (
  `publishing` INT(11) NOT NULL DEFAULT '' COMMENT 'Издательство',
  `book` INT(11) NOT NULL DEFAULT '' COMMENT 'Название книги',
  INDEX `FK_publishing_idx` (`publishing` ASC) VISIBLE,
  INDEX `FK_book_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `FK_publishing`
    FOREIGN KEY (`publishing`)
    REFERENCES `my_home_lib`.`publishing` (`publishing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_book`
    FOREIGN KEY (`book`)
    REFERENCES `my_home_lib`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
