-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 12:44:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_home_lib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_home_lib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_home_lib` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `my_home_lib` ;

-- -----------------------------------------------------
-- Table `my_home_lib`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`author` (
  `name` VARCHAR(150) NOT NULL DEFAULT '' COMMENT 'Автор',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `author` USING BTREE (`name`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Автор книги';


-- -----------------------------------------------------
-- Table `my_home_lib`.`author_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`author_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `book` VARCHAR(50) NOT NULL COMMENT 'Название книги',
  `author` VARCHAR(150) NOT NULL COMMENT 'Автор',
  PRIMARY KEY (`id`),
  INDEX `FK_author_data_author` (`author` ASC) VISIBLE,
  CONSTRAINT `FK_author_data_author`
    FOREIGN KEY (`author`)
    REFERENCES `my_home_lib`.`author` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_home_lib`.`cover`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`cover` (
  `name` VARCHAR(50) NOT NULL COMMENT 'Обложка, переплёт',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `cover` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Обложка, переплёт';


-- -----------------------------------------------------
-- Table `my_home_lib`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`collection` (
  `name` VARCHAR(50) NOT NULL COMMENT 'Сборник, коллекция',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `collection` USING BTREE (`name`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Сборник, коллекция';


-- -----------------------------------------------------
-- Table `my_home_lib`.`collection_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`collection_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `book` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Название книги',
  `collection` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Сборник, коллекция',
  PRIMARY KEY (`id`),
  INDEX `FK__collection` (`collection` ASC) VISIBLE,
  CONSTRAINT `FK__collection`
    FOREIGN KEY (`collection`)
    REFERENCES `my_home_lib`.`collection` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Сборник, коллекция';


-- -----------------------------------------------------
-- Table `my_home_lib`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`genre` (
  `name` VARCHAR(50) NOT NULL COMMENT 'Жанр',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `genre` USING BTREE (`name`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Жанр книги';


-- -----------------------------------------------------
-- Table `my_home_lib`.`genre_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`genre_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `book` VARCHAR(50) NOT NULL COMMENT 'Название книги',
  `genre` VARCHAR(50) NOT NULL COMMENT 'Жанр',
  PRIMARY KEY (`id`),
  INDEX `FK_genre_data_genre` (`genre` ASC) VISIBLE,
  CONSTRAINT `FK_genre_data_genre`
    FOREIGN KEY (`genre`)
    REFERENCES `my_home_lib`.`genre` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_home_lib`.`publishing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`publishing` (
  `name` VARCHAR(50) NOT NULL COMMENT 'Издательство',
  PRIMARY KEY USING BTREE (`name`),
  UNIQUE INDEX `publishing` USING BTREE (`name`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Издательство';


-- -----------------------------------------------------
-- Table `my_home_lib`.`publishing_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`publishing_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `book` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Название книги',
  `publishing` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Издательство',
  PRIMARY KEY (`id`),
  INDEX `FK_publishing_data_publishing` (`publishing` ASC) VISIBLE,
  CONSTRAINT `FK_publishing_data_publishing`
    FOREIGN KEY (`publishing`)
    REFERENCES `my_home_lib`.`publishing` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_home_lib`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_home_lib`.`book` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `book` VARCHAR(50) NOT NULL COMMENT 'Название книги',
  `author` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Автор',
  `publishing` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Издательство',
  `year` DATE NULL DEFAULT NULL COMMENT 'Год выпуска',
  `bookcase` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Полка, стеллаж',
  `numpage` INT(11) NULL DEFAULT NULL COMMENT 'Количествово страниц',
  `collection` VARCHAR(50) NULL DEFAULT '0' COMMENT 'Сбоник, коллекция',
  `genre` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Жанр',
  `cover` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Обложка, переплёт',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `FK_book_author_data` (`author` ASC) VISIBLE,
  INDEX `FK_book_publishing_data` (`publishing` ASC) VISIBLE,
  INDEX `FK_book_genre_data` (`genre` ASC) VISIBLE,
  INDEX `FK_book_collection_data` (`collection` ASC) VISIBLE,
  INDEX `FK_book_cover` (`cover` ASC) VISIBLE,
  CONSTRAINT `FK_book_cover`
    FOREIGN KEY (`cover`)
    REFERENCES `my_home_lib`.`cover` (`name`),
  CONSTRAINT `FK_book_author_data`
    FOREIGN KEY (`author`)
    REFERENCES `my_home_lib`.`author_data` (`author`),
  CONSTRAINT `FK_book_collection_data`
    FOREIGN KEY (`collection`)
    REFERENCES `my_home_lib`.`collection_data` (`collection`),
  CONSTRAINT `FK_book_genre_data`
    FOREIGN KEY (`genre`)
    REFERENCES `my_home_lib`.`genre_data` (`genre`),
  CONSTRAINT `FK_book_publishing_data`
    FOREIGN KEY (`publishing`)
    REFERENCES `my_home_lib`.`publishing_data` (`publishing`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Коллекция книг';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
