Vagrant.configure("2") do |config|
  #config.vm.box = "debian11-4.1.4"
  config.vm.box = "generic/debian11"
  
  config.vm.network "forwarded_port", host: 5432, guest: 5432, id: "pgsql"
  config.vm.network "forwarded_port", host: 80, guest: 80, id: "www"

  config.vm.synced_folder "shared/", "/shared", owner: "vagrant",  group: "vagrant", mount_options: ["dmode=777", "fmode=666"]

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    TZ=Europe/Moscow
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    
    cd /home/vagrant && \
    cp -f /shared/config/vagrant_bashrc .bashrc && \
    cp /shared/config/.bash_aliases .bash_aliases && \
    cp /shared/config/.selected_editor .selected_editor && \
    cp /shared/config/.vimrc .vimrc && \
    chown -R vagrant:vagrant /home/vagrant && \
    echo "User vagrant config ok..."

    cp -f /shared/config/root_bashrc /root/.bashrc && \
    cp /shared/config/.selected_editor /root/.selected_editor && \
    cp /shared/config/.vimrc /root/.vimrc && \
    echo "User root config ok..."
    echo
    echo "Install basic soft by script /shared/config/basic_soft_install.bash"
    echo "Install docker by script /shared/config/docker_install.bash"
    
    apt-get update
    apt-get -y upgrade
    apt-get -y install vim
    apt-get -y install mc
    apt-get -y install curl
    apt-get -y install gnupg2
    apt-get -y install apt-transport-https
    apt-get -y install ca-certificates
    apt-get -y install software-properties-common
    echo "Basic packages install is finished..."
    
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin && usermod -aG docker vagrant
    
    docker run hello-world
  SHELL
end
