# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$bootstrap = <<-SHELL		
		apt-get -y update
        apt-get -y upgrade
        apt-get -y install software-properties-common
		add-apt-repository ppa:ondrej/php -y
		apt-get -y update
        apt-get -y install php8.0-{fpm,common,cli,curl,intl,mysql,readline,xml,mbstring,xdebug}
		apt-get -y install nginx
        apt-get -y install mysql-server mysql-client
        sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
        service mysql restart
		sudo service nginx restart
SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "test_os"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.synced_folder "./www", "/www"
  config.vm.synced_folder "nginx_conf/", "/etc/nginx/conf.d"  

  config.vm.provision "shell", inline: $bootstrap
end
