
services:
    db:
        build: ./db
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: vagrant
            MARIADB_PASSWORD: vagrant
            MARIADB_DATABASE: library
        hostname: c_sql
        ports:
            - 3306:3306
        volumes:
            - v_mysql_data:/var/lib/mysql
            - /tmp:/var/tmp
        networks:
            - n_my_net

    web:
        build: ./web
        hostname: c_web
        ports:
            - 8033:8033
        volumes:
            - /home/vagrant/site/html:/var/www/html
            - /home/vagrant/site/conf:/etc/nginx/conf.d
        networks:
            - n_my_net

    php:
       build: ./php
       hostname: c_php
       ports:
           - 9033:9033
       volumes:
           - /home/vagrant/site/html:/var/www/html
       networks:
           - n_my_net

volumes:
   v_mysql_data:

networks:
    n_my_net:
