
services:
    php:
       build: ./php
       hostname: c_php
       ports:
           - "9000:9000"
       volumes:
           - /home/vagrant/app:/var/www/html
       networks:
           - n_my_net
            
    web:
        build: ./web
        hostname: c_web
        ports:
            - "8033:80"
        volumes:
            - /home/vagrant/app:/var/www/html
            - /shared/config/nginx:/etc/nginx/conf.d
        networks:
            - n_my_net

networks:
    n_my_net:
