
services:
    db:
        build: ./db
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: vagrant
            MARIADB_PASSWORD: vagrant
            MARIADB_DATABASE: tasktracker
        hostname: c_sql
        ports:
            - "3306:3306"
        volumes:
            - v_mysql_data:/var/lib/mysql
            - /shared/initdb:/docker-entrypoint-initdb.d
        networks:
            - n_my_net

    php:
       build: ./php
       hostname: c_php
       ports:
           - "9000:9000"
       volumes:
           - /home/vagrant/app:/var/www/html
       networks:
           - n_my_net
            
    web:
        build: ./web
        hostname: c_web
        ports:
            - "8033:80"
        volumes:
            - /home/vagrant/app:/var/www/html
            - /shared/config/nginx:/etc/nginx/conf.d
        networks:
            - n_my_net
            
volumes:
   v_mysql_data:

networks:
    n_my_net:
