
services:
    php:
       build: ./php81
       hostname: c_php
       ports:
           - 9033:9033
       volumes:
           - /home/vagrant/docker/web/www:/var/www
       networks:
           - n_my_net
            
    web:
        build: ./web
        hostname: c_web
        ports:
            - 8033:8033
        volumes:
            - /home/vagrant/docker/web/www:/var/www
            - /home/vagrant/docker/web/conf:/etc/nginx/conf.d
        networks:
            - n_my_net
            
volumes:
   v_pgsql_data:

networks:
    n_my_net:
