
services:
    db:
        build: ./pgsql
        environment:
            POSTGRES_PASSWORD: qwerty
        ports:
            - "5432:5432"
        volumes:
            - v_pgsql_data:/var/lib/postgresql/data
            - /shared/tmp:/tmp
        networks:
            - n_my_net
        command: "-c timezone='Europe/Moscow' -c log_timezone='Europe/Moscow'"

    php:
       build: ./php81
       hostname: c_php
       ports:
           - 9000:9000
       volumes:
           - /home/vagrant/docker/web/www:/var/www
       networks:
           - n_my_net
            
    web:
        build: ./web
        hostname: c_web
        ports:
            - 8033:8033
        volumes:
            - /home/vagrant/docker/web/www:/var/www
            - /home/vagrant/docker/web/conf:/etc/nginx/conf.d
        networks:
            - n_my_net
            
volumes:
   v_pgsql_data:

networks:
    n_my_net:
