
services:
    db:
        build: ./pgsql
        environment:
            POSTGRES_PASSWORD: qwerty
        ports:
            - "5432:5432"
        volumes:
            - v_pgsql_data:/var/lib/postgresql/data
            - /shared/tmp:/var/tmp
        networks:
            - n_my_net
        command: "-c timezone='Europe/Moscow' -c log_timezone='Europe/Moscow'"

    php:
       build: ./php
       hostname: c_php
       ports:
           - 9000:9000
       volumes:
           - /var/www:/var/www
       networks:
           - n_my_net
            
    web:
        image: nginx
        hostname: c_web
        ports:
            - 80:80
        volumes:
            - /var/www:/var/www
            - /shared/www/sites-conf:/etc/nginx/conf.d
        networks:
            - n_my_net
            
volumes:
   v_pgsql_data:

networks:
    n_my_net:
